name: CI
on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: rc

      - name: check format
        run: deno fmt --check

      - name: lint
        run: deno lint

      - name: test
        run: deno test -A --permit-no-files

